var quizData = [
    {
        question: "What are the types of corals?",
        a: "Atolls,Vascular,Barrier,Elkhorn",
        b: "Atolls,Fringing,Barrier,Patch",
        c: "Elkhorn,Staghorn,Finger,Brain",
        d: "Sea whips,Sea plumes,Sea fans,Staghorn",
        correct: "b",
    },
    {
        question: "What is the skeletal cup made of?",
        a: "Calcium phosphate",
        b: "Calcium gluconate",
        c: "Calcium carbonate",
        d: "Calcium citrate",
        correct: "c",
    },
    {
        question: "What are the factors required for coral reef formation?",
        a: "shallow,warm,clear waters,high wave action",
        b: "tropical climate",
        c: "proximity to the equator",
        d: "biodiversity",
        correct: "a",
    },
    {
        question: "What is symbiosis?",
        a: "the process in which plants make energy",
        b: "a relationship where both organisms benefit",
        c: "a relationship between two organisms",
        d: "the erosion of rocks",
        correct: "c",
    },
    {
        question: "What is mutuallism?",
        a: "a relationship between two organisms",
        b: "the process in which plants make energy",
        c: "the erosion of rocks",
        d: "a relationship where both organisms benefit",
        correct: "d",
    },
    {
        question: "What do zooxanthallae provide to the coral?",
        a: "colour,oxygen,food",
        b: "protection,carbon dioxide",
        c: "colour,food,protection",
        d: "carbon dioxide,food",
        correct: "a",
    },
    {
        question: "What do coral provide to the zooxanthallae?",
        a: "carbon dioxide,food",
        b: "protection,carbon dioxide",
        c: "colour,food,protection",
        d: "colour,oxygen,food",
        correct: "b",
    },
    {
        question: "Which of the following highlights the importance of coral?",
        a: "provides food for consumption",
        b: "protection against erosion",
        c: "stabilizing sediments",
        d: "recreation",
        correct: "a",
    },
    {
        question: "Which of these ways can be used to conserve coral?",
        a: "illegal fishing",
        b: "evading taxes",
        c: "using Marine Protected Areas",
        d: "coral bleaching",
        correct: "c",
    },
    {
        question: "What are mangroves?",
        a: "rainforests",
        b: "wetland ecosystems",
        c: "rock like formations",
        d: "underwater volcanoes",
        correct: "b",
    },
    {
        question: "Which type of mangrove has specialized roots called pneumatophores?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "d",
    },
    {
        question: "Which type of mangrove has prop roots?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "a",
    },
    {
        question: "Which type of mangrove is named '𝘓𝘢𝘨𝘶𝘯𝘤𝘶𝘭𝘢𝘳𝘪𝘢 𝘳𝘢𝘤𝘦𝘮𝘰𝘴𝘢'?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "c",
    },
    {
        question: "Which type of mangrove is named '𝘙𝘩𝘪𝘻𝘰𝘱𝘩𝘰𝘳𝘢 𝘮𝘢𝘯𝘨𝘭𝘦'?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "a",
    },
    {
        question: "Which type of mangrove is named '𝘊𝘰𝘯𝘰𝘤𝘢𝘳𝘱𝘶𝘴 𝘦𝘳𝘦𝘤𝘵𝘶𝘴'?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "b",
    },
    {
        question: "Which type of mangrove is named '𝘈𝘷𝘪𝘤𝘦𝘯𝘯𝘪𝘢 𝘨𝘦𝘳𝘮𝘪𝘯𝘢𝘯𝘴'?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "d",
    },
    {
        question: "Which type of mangrove has thick waxy cuticles on leaves?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "a",
    },
    {
        question: "Which type of mangrove has propagules?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "a",
    },
    {
        question: "Which type of mangrove has bell shaped flowers?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "c",
    },
    {
        question: "Which type of mangrove has ball like cluster flowers?",
        a: "red",
        b: "buttonwood",
        c: "white",
        d: "black",
        correct: "b",
    },
    {
        question: "In what order do mangroves grow from the ocean?",
        a: "black,buttonwood,red,white",
        b: "buttonwood,white,red,black",
        c: "red,black,white,buttonwood",
        d: "red,white,black,buttonwood",
        correct: "c",
    },
    {
        question: "What are halophytes?",
        a: "organisms that live in harsh saline enviroments",
        b: "plants that grow in water",
        c: "organisms that eat meat and plants",
        d: "organisms with one cell",
        correct: "a",
    },
    {
        question: "What does vivaparous mean?",
        a: "plants that grow in water",
        b: "organisms that eat meat and plants",
        c: "when the seed remains attached to the plant til it grows roots",
        d: "special vertical breathing roots",
        correct: "c",
    },
    {
        question: "What are pneumatophores?",
        a: "plants that grow in water",
        b: "special vertical breathing roots",
        c: "breathing pores that cover prop roots",
        d: "fruit found in red mangroves used for germination",
        correct: "b",
    },
    {
        question: "What are lenticels?",
        a: "plants that grow in water",
        b: "special vertical breathing roots",
        c: "breathing pores that cover prop roots",
        d: "fruits found in red mangroves used for germination",
        correct: "c",
    },
    {
        question: "What are propagules?",
        a: "plants that grow in water",
        b: "special vertical breathing roots",
        c: "breathing pores that cover prop roots",
        d: "fruits found in red mangroves used for germination",
        correct: "d",
    },
    {
        question: "What is a cuticle?",
        a: "a layer of substance that reflects heat and reduces water loss",
        b: "plants that grow in water",
        c: "fruits found in red mangroves used for germination",
        d: "special vertical breathing roots",
        correct: "a",
    },
    {
        question: "What importance do mangroves have?",
        a: "breaking tides",
        b: "filters nutrients from the water",
        c: "stops pollution",
        d: "recreation",
        correct: "b",
    },
    {
        question: "What direction is leeward?",
        a: "north",
        b: "south",
        c: "west",
        d: "east",
        correct: "d",
    },
    {
        question: "What direction is windward?",
        a: "north",
        b: "south",
        c: "west",
        d: "east",
        correct: "c",
    },
    {
        question: "Which of these is in the correct order from the ocean?",
        a: "Low,Intertidal,High,Pioneer,Fixed dune,Seagrape,Scrub woodlands",
        b: "High,Intertidal,Low,Pioneer,Fixed dune,Seagrape,Scrub woodlands",
        c: "High,Intertidal,Low,Pioneer,Fixed dune,Scrub woodlands,Seagrape",
        d: "Low,Intertidal,High,Fixed dune,Pioneer,Scrub woodlands,Seagrape",
        correct: "a",
    },
    {
        question: "Which of these organisms live in the sandy shore?",
        a: "Periwinkles",
        b: "Starfish",
        c: "Brown seaweed",
        d: "chitons",
        correct: "b",
    },
    {
        question: "What are seagrass meadows?",
        a: "angiosperms that live completely underwater",
        b: "a type of grass that grows underwater",
        c: "angiosperms with xylems and phloem",
        d: "rock like formations",
        correct: "a",
    },
    {
        question: "What does vascular mean?",
        a: "angiosperms that live completely underwater",
        b: "a type of grass that grows underwater",
        c: "angiosperms with xylems and phloem",
        d: "rock like formations",
        correct: "c",
    },
    {
        question: "Which of these characteristics do seaweed possess?",
        a: "vascular",
        b: "rhizomes",
        c: "chloroplast",
        d: "reproduce using spores",
        correct: "d",
    },
    {
        question: "What does brackish mean?",
        a: "mixture of salty and fresh water",
        b: "the act of catching aquatic organisms",
        c: "the ability to grow in a tropical climate",
        d: "the ability to reproduce using spores",
        correct: "a",
    },
    {
        question: "What is fishing?",
        a: "mixture of salty and fresh water",
        b: "the act of catching aquatic organisms",
        c: "the ability to grow in a tropical climate",
        d: "the ability to reproduce using spores",
        correct: "b",
    },
    {
        question: "What are the types of fishing?",
        a: "selective,non-selective",
        b: "rural,urban,mixed",
        c: "netting,traps,spearing",
        d: "subsistence,commercial,sport",
        correct: "d",
    },
    {
        question: "What is the closed season for conch?",
        a: "Jun 1 - Oct 15",
        b: "Apr 1 - Jul 31",
        c: "Aug 1 - Mar 31",
        d: "no season",
        correct: "d",
    },
    {
        question: "What is the closed season for lobster?",
        a: "Jun 1 - Oct 15",
        b: "Apr 1 - Jul 31",
        c: "Aug 1 - Mar 31",
        d: "no season",
        correct: "c",
    },
    {
        question: "What is the closed season for crawfish?",
        a: "Jun 1 - Oct 15",
        b: "Apr 1 - Jul 31",
        c: "Aug 1 - Mar 31",
        d: "no season",
        correct: "b",
    },
    {
        question: "What is the closed season for crab?",
        a: "Jun 1 - Oct 15",
        b: "Apr 1 - Jul 31",
        c: "Aug 1 - Mar 31",
        d: "Dec 1 - Feb 28",
        correct: "a",
    },
    {
        question: "What is the closed season for grouper?",
        a: "Jun 1 - Oct 15",
        b: "Apr 1 - Jul 31",
        c: "Aug 1 - Mar 31",
        d: "Dec 1 - Feb 28",
        correct: "d",
    },
    {
        question: "What is the scientific name for grouper?",
        a: "𝘚𝘵𝘳𝘰𝘮𝘣𝘶𝘴 𝘨𝘪𝘨𝘢𝘴",
        b: "𝘈𝘭𝘣𝘶𝘭𝘢 𝘷𝘶𝘭𝘱𝘦𝘴",
        c: "𝘌𝘱𝘪𝘯𝘦𝘱𝘩𝘦𝘭𝘶𝘴 𝘴𝘵𝘳𝘪𝘢𝘵𝘶𝘴",
        d: "𝘊𝘢𝘳𝘥𝘪𝘴𝘰𝘮𝘢 𝘨𝘶𝘢𝘯𝘩𝘶𝘮𝘪",
        correct: "c",
    },
    {
        question: "What is the scientific name for conch?",
        a: "𝘚𝘵𝘳𝘰𝘮𝘣𝘶𝘴 𝘨𝘪𝘨𝘢𝘴",
        b: "𝘈𝘭𝘣𝘶𝘭𝘢 𝘷𝘶𝘭𝘱𝘦𝘴",
        c: "𝘌𝘱𝘪𝘯𝘦𝘱𝘩𝘦𝘭𝘶𝘴 𝘴𝘵𝘳𝘪𝘢𝘵𝘶𝘴",
        d: "𝘊𝘢𝘳𝘥𝘪𝘴𝘰𝘮𝘢 𝘨𝘶𝘢𝘯𝘩𝘶𝘮𝘪",
        correct: "a",
    },
    {
        question: "What is the scientific name for crab?",
        a: "𝘚𝘵𝘳𝘰𝘮𝘣𝘶𝘴 𝘨𝘪𝘨𝘢𝘴",
        b: "𝘈𝘭𝘣𝘶𝘭𝘢 𝘷𝘶𝘭𝘱𝘦𝘴",
        c: "𝘗𝘢𝘯𝘶𝘭𝘪𝘳𝘶𝘴 𝘢𝘳𝘨𝘶𝘴",
        d: "𝘊𝘢𝘳𝘥𝘪𝘴𝘰𝘮𝘢 𝘨𝘶𝘢𝘯𝘩𝘶𝘮𝘪",
        correct: "d",
    },
    {
        question: "What is the scientific name for bonefish?",
        a: "𝘚𝘵𝘳𝘰𝘮𝘣𝘶𝘴 𝘨𝘪𝘨𝘢𝘴",
        b: "𝘈𝘭𝘣𝘶𝘭𝘢 𝘷𝘶𝘭𝘱𝘦𝘴",
        c: "𝘗𝘢𝘯𝘶𝘭𝘪𝘳𝘶𝘴 𝘢𝘳𝘨𝘶𝘴",
        d: "𝘊𝘢𝘳𝘥𝘪𝘴𝘰𝘮𝘢 𝘨𝘶𝘢𝘯𝘩𝘶𝘮𝘪",
        correct: "b",
    },
    {
        question: "What is the scientific name for lobster?",
        a: "𝘚𝘵𝘳𝘰𝘮𝘣𝘶𝘴 𝘨𝘪𝘨𝘢𝘴",
        b: "𝘈𝘭𝘣𝘶𝘭𝘢 𝘷𝘶𝘭𝘱𝘦𝘴",
        c: "𝘗𝘢𝘯𝘶𝘭𝘪𝘳𝘶𝘴 𝘢𝘳𝘨𝘶𝘴",
        d: "𝘊𝘢𝘳𝘥𝘪𝘴𝘰𝘮𝘢 𝘨𝘶𝘢𝘯𝘩𝘶𝘮𝘪",
        correct: "c",
    },
    {
        question: "Which of these is true about land crabs?",
        a: "used only for gamefishing",
        b: "they spawn from June to November",
        c: "changes color between normal and bicolor",
        d: "males have a verge",
        correct: "b",
    },
    {
        question: "Which of these is true about groupers?",
        a: "used only for gamefishing",
        b: "they spawn from June to November",
        c: "changes color between normal and bicolor",
        d: "males have a verge",
        correct: "c",
    },
    {
        question: "Which of these is true about conch?",
        a: "used only for gamefishing",
        b: "they clean reefs",
        c: "changes color between normal and bicolor",
        d: "males have a verge",
        correct: "d",
    },
    {
        question: "Which of these is true about lobsters?",
        a: "used only for gamefishing",
        b: "they clean reefs",
        c: "changes color between normal and bicolor",
        d: "males have a verge",
        correct: "b",
    },
    {
        question: "Which of these is true about bonefish?",
        a: "used only for gamefishing",
        b: "they clean reefs",
        c: "changes color between normal and bicolor",
        d: "males have a verge",
        correct: "a",
    },
    {
        question: "What is the chrystalline style?",
        a: "line of conch eggs",
        b: "types of claws used to communication",
        c: "shedding outer shell underneath hard shell",
        d: "change in body from from one state to another",
        correct: "a",
    },
    {
        question: "What is metamorphasis?",
        a: "line of conch eggs",
        b: "types of claws used to communication",
        c: "shedding outer shell underneath hard shell",
        d: "change in body from from one state to another",
        correct: "d",
    },
    {
        question: "What is molting?",
        a: "line of conch eggs",
        b: "types of claws used to communication",
        c: "shedding outer shell underneath hard shell",
        d: "change in body from from one state to another",
        correct: "c",
    },
    {
        question: "What is aquaculture?",
        a: "migration of species to adjacent fishing areas",
        b: "farming of aquatic organisms in fresh water enviroments",
        c: "farming of aquatic organisms in saltwater enviroments",
        d: "increase of chemichals in tissues of organisms",
        correct: "b",
    },
    {
        question: "What is biocummulation?",
        a: "migration of species to adjacent fishing areas",
        b: "farming of aquatic organisms in fresh water enviroments",
        c: "farming of aquatic organisms in saltwater enviroments",
        d: "increase of chemichals in tissues of organisms",
        correct: "d",
    },
    {
        question: "What is spillover?",
        a: "migration of species to adjacent fishing areas",
        b: "farming of aquatic organisms in fresh water enviroments",
        c: "farming of aquatic organisms in saltwater enviroments",
        d: "increase of chemichals in tissues of organisms",
        correct: "a",
    },
    {
        question: "What is mariculture?",
        a: "migration of species to adjacent fishing areas",
        b: "farming of aquatic organisms in fresh water enviroments",
        c: "farming of aquatic organisms in saltwater enviroments",
        d: "increase of chemichals in tissues of organisms",
        correct: "c",
    },
    {
        question: "Which method of fishing is not selective?",
        a: "netting",
        b: "hooks and line",
        c: "pots and trap",
        d: "spear and hawaiin sling",
        correct: "a",
    },
    {
        question: "Which method of fishing is a cause of ghost fishing?",
        a: "netting",
        b: "hooks and line",
        c: "pots and trap",
        d: "spear and hawaiin sling",
        correct: "c",
    },
    {
        question: "Which method of fishing requires a large vessel?",
        a: "netting",
        b: "hooks and line",
        c: "pots and trap",
        d: "spear and hawaiin sling",
        correct: "a",
    },
];