var quizData = [
    {
        question: "What is continental drift?",
        a: "all land",
        b: "where plates meet,most earthquakes occur and volcanoes form",
        c: "the theory that suggests that the continents were once one landmass and have moved to their current positions over time.",
        d: "slabs of earth's crust that float on the upper mantle",
        correct: "c",
    },
    {
        question: "What is a plate boundary?",
        a: "all land",
        b: "where plates meet,most earthquakes occur and volcanoes form",
        c: "the theory that suggests that the continents were once one landmass and have moved to their current positions over time.",
        d: "slabs of earth's crust that float on the upper mantle",
        correct: "b",
    },
    {
        question: "What is a plate?",
        a: "all land",
        b: "where plates meet,most earthquakes occur and volcanoes form",
        c: "the theory that suggests that the continents were once one landmass and have moved to their current positions over time.",
        d: "slabs of earth's crust that float on the upper mantle",
        correct: "d",
    },
    {
        question: "What does Pangaea mean?",
        a: "all land",
        b: "where plates meet,most earthquakes occur and volcanoes form",
        c: "the theory that suggests that the continents were once one landmass and have moved to their current positions over time.",
        d: "slabs of earth's crust that float on the upper mantle",
        correct: "a",
    },
    {
        question: "Which of these is a characteristic of continental crust?",
        a: "older",
        b: "heavier",
        c: "can sink",
        d: "constantly bieng destroyed",
        correct: "a",
    },
    {
        question: "Which of these is a characteristic of oceanic crust?",
        a: "lighter",
        b: "permanent",
        c: "denser rocks",
        d: "cannot sink",
        correct: "c",
    },
    {
        question: "What is oceanic crust made of?",
        a: "slate",
        b: "basalt",
        c: "limestone",
        d: "granite",
        correct: "b",
    },
    {
        question: "What is continental crust made of?",
        a: "slate",
        b: "basalt",
        c: "limestone",
        d: "granite",
        correct: "d",
    },
    {
        question: "What is a constructive plate boundary?",
        a: "two plates move away from each other and magma pours in to fill gaps",
        b: "two plates move side by side",
        c: "two plates containing continental crust move upwards",
        d: "one plate moves under the other",
        correct: "a",
    },
    {
        question: "What is a destructive boundary collision zone?",
        a: "two plates move away from each other and magma pours in to fill gaps",
        b: "two plates move side by side",
        c: "two plates containing continental crust move upwards",
        d: "one plate moves under the other",
        correct: "c",
    },
    {
        question: "What is a destructive boundary subduction zone?",
        a: "two plates move away from each other and magma pours in to fill gaps",
        b: "two plates move side by side",
        c: "two plates containing continental crust move upwards",
        d: "one plate moves under the other",
        correct: "d",
    },
    {
        question: "What is a conservative plate boundary?",
        a: "two plates move away from each other and magma pours in to fill gaps",
        b: "two plates move side by side",
        c: "two plates containing continental crust move upwards",
        d: "one plate moves under the other",
        correct: "b",
    },
    {
        question: "Which of these is not a part of the evidence that supports continental drift?",
        a: "alignment of continents",
        b: "fossil evidence",
        c: "age of the ocean floor",
        d: "rock type",
        correct: "c",
    },
    {
        question: "Which of these is not a part of the evidence that supports plate tectonics?",
        a: "rock structure",
        b: "paleomagnetics",
        c: "pattern of seismic and volcanic activity",
        d: "topography of the ocean floor",
        correct: "a",
    },
    {
        question: "What is the theory of plate tectonics?",
        a: "the crust is divided into plates and they are carried by convection currents in the athenosphere",
        b: "areas where lave spread out to form new crust",
        c: "a layer composed of a mixture of gases which surround earth",
        d: "the term drift implies that the large pieces of crust are floating aimlessly and are not bieng controlled by anything",
        correct: "a",
    },
    {
        question: "What is the flaw of this theory?",
        a: "the crust is divided into plates and they are carried by convection currents in the athenosphere",
        b: "areas where lave spread out to form new crust",
        c: "a layer composed of a mixture of gases which surround earth",
        d: "the term drift implies that the large pieces of crust are floating aimlessly and are not bieng controlled by anything",
        correct: "d",
    },
    {
        question: "What is the submarine ridge?",
        a: "the crust is divided into plates and they are carried by convection currents in the athenosphere",
        b: "areas where lave spread out to form new crust",
        c: "a layer composed of a mixture of gases which surround earth",
        d: "the term drift implies that the large pieces of crust are floating aimlessly and are not bieng controlled by anything",
        correct: "b",
    },
    {
        question: "What is the atmosphere?",
        a: "the crust is divided into plates and they are carried by convection currents in the athenosphere",
        b: "areas where lave spread out to form new crust",
        c: "a layer composed of a mixture of gases which surround earth",
        d: "the term drift implies that the large pieces of crust are floating aimlessly and are not bieng controlled by anything",
        correct: "c",
    },
    {
        question: "Which of these is false?",
        a: "mesosphere - mantle",
        b: "lithosphere - crust",
        c: "athenosphere - crust",
        d: "barysphere - core",
        correct: "c",
    },
    {
        question: "Which of these is false?",
        a: "normal fault - from tension",
        b: "reverse fault - from compression",
        c: "tear fault - from shearing",
        d: "tear fault - from compression",
        correct: "d",
    },
    {
        question: "Which of these is not a part of a fault?",
        a: "joint",
        b: "fault scarp",
        c: "hanging wall",
        d: "foot wall",
        correct: "a",
    },
    {
        question: "What is a fault?",
        a: "pressure built up due to plate tectonic movement",
        b: "surfaces along which rocks break and displaced, by tentional and compressional forces",
        c: "force that pushes 2 pieces of crust together",
        d: "cracks in rocks that coincide with a line of weakness",
        correct: "b",
    },
    {
        question: "What is compression?",
        a: "pressure built up due to plate tectonic movement",
        b: "surfaces along which rocks break and displaced, by tentional and compressional forces",
        c: "force that pushes 2 pieces of crust together",
        d: "cracks in rocks that coincide with a line of weakness",
        correct: "c",
    },
    {
        question: "What is tension?",
        a: "pressure built up due to plate tectonic movement",
        b: "surfaces along which rocks break and displaced, by tentional and compressional forces",
        c: "force that pushes 2 pieces of crust together",
        d: "cracks in rocks that coincide with a line of weakness",
        correct: "a",
    },
    {
        question: "What is a joint?",
        a: "pressure built up due to plate tectonic movement",
        b: "surfaces along which rocks break and displaced, by tentional and compressional forces",
        c: "force that pushes 2 pieces of crust together",
        d: "cracks in rocks that coincide with a line of weakness",
        correct: "d",
    },
    {
        question: "What is a rift valley?",
        a: "uplifted blocks that are horizontal when they form",
        b: "2 parallel fault occurs and block between them drops or they rise above it",
        c: "uplifted blocks that are tilted when they form",
        d: "when faulting is accompanied by upward or downward movements of adjoining parts of the crust",
        correct: "b",
    },
    {
        question: "What is a horst?",
        a: "uplifted blocks that are horizontal when they form",
        b: "2 parallel fault occurs and block between them drops or they rise above it",
        c: "uplifted blocks that are tilted when they form",
        d: "when faulting is accompanied by upward or downward movements of adjoining parts of the crust",
        correct: "a",
    },
    {
        question: "What is a tilt block?",
        a: "uplifted blocks that are horizontal when they form",
        b: "2 parallel fault occurs and block between them drops or they rise above it",
        c: "uplifted blocks that are tilted when they form",
        d: "when faulting is accompanied by upward or downward movements of adjoining parts of the crust",
        correct: "c",
    },
    {
        question: "What is an escarpment?",
        a: "uplifted blocks that are horizontal when they form",
        b: "2 parallel fault occurs and block between them drops or they rise above it",
        c: "uplifted blocks that are tilted when they form",
        d: "when faulting is accompanied by upward or downward movements of adjoining parts of the crust",
        correct: "d",
    },
    {
        question: "What is an unconformity?",
        a: "land mass with an elevation over 1000ft",
        b: "erosion that causes mountains to flatten over millions of years",
        c: "surface that divides two suites of rocks",
        d: "deformation of the earth's crust",
        correct: "c",
    },
    {
        question: "What is a mountain?",
        a: "land mass with an elevation over 1000ft",
        b: "erosion that causes mountains to flatten over millions of years",
        c: "surface that divides two suites of rocks",
        d: "deformation of the earth's crust",
        correct: "a",
    },
    {
        question: "What is denudation?",
        a: "land mass with an elevation over 1000ft",
        b: "erosion that causes mountains to flatten over millions of years",
        c: "surface that divides two suites of rocks",
        d: "deformation of the earth's crust",
        correct: "b",
    },
    {
        question: "What is distrophism?",
        a: "land mass with an elevation over 1000ft",
        b: "erosion that causes mountains to flatten over millions of years",
        c: "surface that divides two suites of rocks",
        d: "deformation of the earth's crust",
        correct: "d",
    },
    {
        question: "What is a syncline/valley?",
        a: "upward part of a fold",
        b: "downward part of a fold",
        c: "sides of a fold",
        d: "line of highest points along a anticline",
        correct: "b",
    },
    {
        question: "What is a anticline/ridges?",
        a: "upward part of a fold",
        b: "downward part of a fold",
        c: "sides of a fold",
        d: "line of highest points along a anticline",
        correct: "a",
    },
    {
        question: "What is a crest?",
        a: "upward part of a fold",
        b: "downward part of a fold",
        c: "sides of a fold",
        d: "line of highest points along a anticline",
        correct: "d",
    },
    {
        question: "What is a limb?",
        a: "upward part of a fold",
        b: "downward part of a fold",
        c: "sides of a fold",
        d: "line of highest points along a anticline",
        correct: "c",
    },
    {
        question: "What is folding?",
        a: "upward part of a fold",
        b: "downward part of a fold",
        c: "sides of a fold",
        d: "line of highest points along a anticline",
        correct: "d",
    },

]