var quizData = [
    {
        question: "What is the symbol for distance?",
        a: "d",
        b: "s",
        c: "t",
        d: "v",
        correct: "b",
    },
    {
        question: "What is the symbol for depth/thickness?",
        a: "d",
        b: "s",
        c: "t",
        d: "v",
        correct: "a",
    },
    {
        question: "What is the symbol for velocity?",
        a: "d",
        b: "s",
        c: "t",
        d: "v",
        correct: "d",
    },
    {
        question: "What is the symbol for time?",
        a: "d",
        b: "s",
        c: "t",
        d: "v",
        correct: "c",
    },
    {
        question: "What is the symbol for current?",
        a: "I",
        b: "ρ",
        c: "T",
        d: "V",
        correct: "a",
    },
    {
        question: "What is the symbol for volume?",
        a: "I",
        b: "ρ",
        c: "T",
        d: "V",
        correct: "d",
    },
    {
        question: "What is the symbol for density?",
        a: "I",
        b: "ρ",
        c: "T",
        d: "V",
        correct: "b",
    },
    {
        question: "What is the symbol for temperature?",
        a: "I",
        b: "ρ",
        c: "T",
        d: "V",
        correct: "c",
    },
    {
        question: "What is the symbol for force?",
        a: "Q",
        b: "P",
        c: "F",
        d: "W",
        correct: "c",
    },
    {
        question: "What is the symbol for charge?",
        a: "Q",
        b: "P",
        c: "F",
        d: "W",
        correct: "a",
    },
    {
        question: "What is the symbol for work?",
        a: "Q",
        b: "P",
        c: "p",
        d: "W",
        correct: "d",
    },
    {
        question: "What is the symbol for power?",
        a: "Q",
        b: "P",
        c: "p",
        d: "W",
        correct: "b",
    },
    {
        question: "What is the symbol for momentum?",
        a: "Q",
        b: "P",
        c: "p",
        d: "W",
        correct: "c",
    },
    {
        question: "What is the SI Unit for power?",
        a: "coulomb",
        b: "watt",
        c: "metres per second",
        d: "ampere",
        correct: "b",
    },
    {
        question: "What is the SI Unit for current?",
        a: "coulomb",
        b: "watt",
        c: "metres per second",
        d: "ampere",
        correct: "d",
    },
    {
        question: "What is the SI Unit for velocity?",
        a: "coulomb",
        b: "watt",
        c: "metres per second",
        d: "ampere",
        correct: "c",
    },
    {
        question: "What is the SI Unit for charge?",
        a: "coulomb",
        b: "watt",
        c: "metres per second",
        d: "ampere",
        correct: "a",
    },
    {
        question: "What is the SI Unit for time?",
        a: "newton",
        b: "newton per kilogram",
        c: "hertz",
        d: "second",
        correct: "d",
    },
    {
        question: "What is the SI Unit for force?",
        a: "newton",
        b: "newton per kilogram",
        c: "hertz",
        d: "second",
        correct: "a",
    },
    {
        question: "What is the SI Unit for frequency?",
        a: "kilogram per metres per second",
        b: "newton per kilogram",
        c: "hertz",
        d: "second",
        correct: "c",
    },
    {
        question: "What is the SI Unit for gravitational field strength?",
        a: "kilogram per metres per second",
        b: "newton per kilogram",
        c: "hertz",
        d: "second",
        correct: "b",
    },
    {
        question: "What is the SI Unit for momentum?",
        a: "kilogram per metres per second",
        b: "newton per kilogram",
        c: "hertz",
        d: "second",
        correct: "a",
    },
    {
        question: "What is the formula for g?",
        a: "g=m*v",
        b: "g=m*a",
        c: "g=F/m",
        d: "g=I*t",
        correct: "c",
    },
    {
        question: "What is the formula for charge?",
        a: "Q=m*v",
        b: "Q=m*a",
        c: "Q=F/m",
        d: "Q=I*t",
        correct: "d",
    },
    {
        question: "What is the formula for momentum?",
        a: "p=m*v",
        b: "p=m*a",
        c: "p=F/m",
        d: "p=I*t",
        correct: "a",
    },
    {
        question: "What is the formula for force?",
        a: "F=m*v",
        b: "F=m*a",
        c: "F=F/m",
        d: "F=I*t",
        correct: "b",
    },
    {
        question: "What is the formula for power?",
        a: "P=s/t",
        b: "P=W/t",
        c: "P=F/A",
        d: "P=hρg",
        correct: "b",
    },
    {
        question: "What is the formula for velocity?",
        a: "v=s/t",
        b: "v=W/t",
        c: "v=F/A",
        d: "v=hρg",
        correct: "a",
    },
    {
        question: "What is the formula for pressure?",
        a: "P=s/t",
        b: "P=W/t",
        c: "P=F/A",
        d: "P=hρg",
        correct: "c",
    },
    {
        question: "What is the formula for liquid pressure?",
        a: "P(liquid)=s/t",
        b: "P(liquid)=W/t",
        c: "P(liquid)=F/A",
        d: "P(liquid)=hρg",
        correct: "d",
    },
    {
        question: "What is the symbol for micro?",
        a: "m",
        b: "mc",
        c: "n",
        d: "d",
        correct: "b",
    },
    {
        question: "What is the symbol for milli?",
        a: "m",
        b: "mc",
        c: "n",
        d: "d",
        correct: "a",
    },
    {
        question: "What is the symbol for nano?",
        a: "m",
        b: "mc",
        c: "n",
        d: "d",
        correct: "c",
    },
    {
        question: "What is the symbol for deci?",
        a: "m",
        b: "mc",
        c: "n",
        d: "d",
        correct: "d",
    },
    {
        question: "What is the symbol for deca?",
        a: "G",
        b: "M",
        c: "h",
        d: "da",
        correct: "d",
    },
    {
        question: "What is the symbol for giga?",
        a: "G",
        b: "M",
        c: "h",
        d: "da",
        correct: "a",
    },
    {
        question: "What is the symbol for mega?",
        a: "G",
        b: "M",
        c: "h",
        d: "da",
        correct: "b",
    },
    {
        question: "What is the symbol for hecta?",
        a: "G",
        b: "M",
        c: "h",
        d: "da",
        correct: "c",
    },
    {
        question: "What is the kinetic theory?",
        a: "matter has mass",
        b: "matter is composed of particles that are in constant motion",
        c: "matter is made up of atoms",
        d: "temperature is proportional to the average kinetic energy",
        correct: "b",
    },
    {
        question: "What is the kinetic definition for temperature?",
        a: "matter has mass",
        b: "matter is composed of particles that are in constant motion",
        c: "matter is made up of atoms",
        d: "temperature is proportional to the average kinetic energy",
        correct: "d",
    },
    {
        question: "What is the motion of solid particles?",
        a: "they dont move",
        b: "move slowly",
        c: "vibrate about fixed positions",
        d: "move rapidly and randomly",
        correct: "c",
    },
    {
        question: "What is the motion of liquid particles?",
        a: "they dont move",
        b: "move slowly",
        c: "vibrate about fixed positions",
        d: "move rapidly and randomly",
        correct: "b",
    },
    {
        question: "What is the motion of gas particles?",
        a: "they dont move",
        b: "move slowly",
        c: "vibrate about fixed positions",
        d: "move rapidly and randomly",
        correct: "d",
    },
    {
        question: "What is the kinetic energy of gas particles?",
        a: "none",
        b: "very small",
        c: "medium amount",
        d: "large amount",
        correct: "d",
    },
    {
        question: "What is the kinetic energy of solid particles?",
        a: "none",
        b: "very small",
        c: "medium amount",
        d: "large amount",
        correct: "b",
    },
    {
        question: "Which of these substances can sublime?",
        a: "Napluthelene",
        b: "Carbon monoxide",
        c: "Aluminum",
        d: "Calcium carbonate",
        correct: "a",
    },
    {
        question: "Which of these is a characteristic of Evaporation?",
        a: "only occurs at the boiling point",
        b: "entire liquid boils",
        c: "slow process",
        d: "no cooling effect",
        correct: "c",
    },
    {
        question: "Which of these is a characteristic of Boiling?",
        a: "can occur at any temperature",
        b: "only affects surface",
        c: "slow process",
        d: "no cooling affect",
        correct: "d",
    },
    {
        question: "Which of these are factors that affect Evaporation?",
        a: "density,gfs,depth",
        b: "surface area,temperature,humidity,rate of wind",
        c: "atmospheric pressure,gravity",
        d: "rate of wind,atmospheric pressure,humidity",
        correct: "b",
    },
    {
        question: "What is the theory of Brownian motion?",
        a: "push or pull acting on an object that changes its motion",
        b: "force that pulls objects to earth",
        c: "random motion of particles in a suspension",
        d: "movement of particles from a region of high concentration to a low while evenly distributed",
        correct: "c",
    },
    {
        question: "What is diffusion?",
        a: "push or pull acting on an object that changes its motion",
        b: "force that pulls objects to earth",
        c: "random motion of particles in a suspension",
        d: "movement of particles from a region of high concentration to a low while evenly distributed",
        correct: "d",
    },
    {
        question: "What is force?",
        a: "push or pull acting on an object that changes its motion",
        b: "force that pulls objects to earth",
        c: "random motion of particles in a suspension",
        d: "movement of particles from a region of high concentration to a low while evenly distributed",
        correct: "a",
    },
    {
        question: "What is gravity?",
        a: "push or pull acting on an object that changes its motion",
        b: "force that pulls objects to earth",
        c: "random motion of particles in a suspension",
        d: "movement of particles from a region of high concentration to a low while evenly distributed",
        correct: "b",
    },
    {
        question: "What do vector quantities have that scalar dont?",
        a: "resistance",
        b: "force",
        c: "magnitude and direction",
        d: "an SI unit",
        correct: "c",
    },
    {
        question: "Which of the following is not a difference between mass and weight?",
        a: "mass doesn't change with location, weight does",
        b: "m is scalar,w is vector",
        c: "m measured with a triple bim balance, w with a spring balance",
        d: "m is affected by g, w is not",
        correct: "d",
    },
    {
        question: "What is the resultant(Net force)?",
        a: "the sum of pressure and atmospheric pressure",
        b: "state of balance",
        c: "when 2 forces acting on the same direction in a straight line are added",
        d: "opposite of acceleration",
        correct: "c",
    },
    {
        question: "What is the total pressure?",
        a: "the sum of pressure and atmospheric pressure",
        b: "state of balance",
        c: "when 2 forces acting on the same direction in a straight line are added",
        d: "opposite of acceleration",
        correct: "a",
    },
    {
        question: "What is equalibrium?",
        a: "the sum of pressure and atmospheric pressure",
        b: "state of balance",
        c: "when 2 forces acting on the same direction in a straight line are added",
        d: "opposite of acceleration",
        correct: "b",
    },
    {
        question: "How much pascals is Atmospheric pressure?",
        a: "150k Pa",
        b: "200k Pa",
        c: "50k Pa",
        d: "100k Pa",
        correct: "d",
    },
    {
        question: "In heat curves, what does a horizontal line suggest about the kinetic energy of particles?",
        a: "the kinetic energy is increasing",
        b: "the kinetic energy is decreasing",
        c: "the kinetic energy is constant",
        d: "the kinetic energy is non-exsistant",
        correct: "c",
    },
]
